### ISSUE TITLE
Timing: Calico policy controller requires restart after k8s API and etcd restart

### ISSUE THREAD

**Issue by rtheis** [projectcalico/k8s-policy#76] opened 2017-03-16 15:53 UTC
Steps to reproduce:
1. Stop k8s API and etcd
2. Wait 60 seconds
3. Start k8s API and etcd
4. Wait 20 seconds
5. Create k8s namespace
6. Create k8s NodePort or LoadBalancer service in the new namespace
7. curl the new service <-- This may hang because felix has `/* WARNING Missing chain */` in iptables.  After restarting the calico policy controller, curl works.

Calico version 2.0.2 is being used with `calico/kube-policy-controller:v0.5.2`.

**Comment by rtheis** [comment] 2017-03-16 15:53
Here are the calico policy controller logs:

```
017-03-16 00:54:51,740 6 ERROR Unahandled exception killed Pod manager
Traceback (most recent call last):
  File "<string>", line 307, in _manage_resource
  File "<string>", line 343, in _watch_resource
  File "site-packages/requests/models.py", line 702, in iter_lines
  File "site-packages/requests/models.py", line 663, in generate
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-16 00:54:51,743 6 WARNING Re-starting watch on resource: Pod
2017-03-16 00:54:51,748 6 ERROR Unahandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 307, in _manage_resource
  File "<string>", line 343, in _watch_resource
  File "site-packages/requests/models.py", line 702, in iter_lines
  File "site-packages/requests/models.py", line 663, in generate
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-16 00:54:51,750 6 WARNING Re-starting watch on resource: Namespace
2017-03-16 00:54:51,750 6 ERROR Unahandled exception killed NetworkPolicy manager
Traceback (most recent call last):
  File "<string>", line 307, in _manage_resource
  File "<string>", line 343, in _watch_resource
  File "site-packages/requests/models.py", line 702, in iter_lines
  File "site-packages/requests/models.py", line 663, in generate
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-16 00:54:51,750 6 WARNING Re-starting watch on resource: NetworkPolicy
2017-03-16 00:54:52,745 6 INFO Syncing 'Pod' objects
2017-03-16 00:54:52,750 6 INFO Syncing 'NetworkPolicy' objects
2017-03-16 00:54:52,751 6 INFO Syncing 'Namespace' objects
```

**Comment by rtheis** [comment] 2017-03-16 15:54
iptables output:
```
Chain felix-p-_4574d49a2816722-i (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* WARNING Missing chain */

Chain felix-p-_4574d49a2816722-o (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* WARNING Missing chain */
```

**Comment by rtheis** [comment] 2017-03-16 16:19
Here is the end of the calico-policy-controller DEBUG log after reproducing the problem:

```
2017-03-16 16:04:13,980 5 INFO Emptied the event queue
2017-03-16 16:04:13,980 5 DEBUG Reading from event queue
```

The k8s API and etc restarts happened around 16:05.

**Comment by fasaxc** [comment] 2017-03-16 17:31
Assigning to Casey for triage.

**Comment by fasaxc** [comment] 2017-03-16 17:47
Looks like the logs stop before the restart, even at debug level.  Smells like the policy agent isn't spotting that its connection has died in a timely manner.  Couple of ideas:

- We may need to force a short read timeout on our poll.
- Could be a side-effect of running the kubelet in a container, for example.  When the container is killed, the traffic gets blackholed instead of generating a clean break.

**Comment by fasaxc** [comment] 2017-03-16 18:19
From a code read, looks like

- we should be specifying the `timeoutSeconds` URL parameter when watching resources so that k8s will give us a clean timeout response
- we should be specifying a slightly longer read timeout on our `session.get()` call
- we should be treating the clean timeout as business-as-usual and retrying the watch
- we should log an error and retry if we hit the other timeout.

The timeout should probably be fairly low (say 10s).

As a PoC, @rtheis tried out this patch for me:
```
diff --git a/controller.py b/controller.py
index 46cc52c..260e87c 100644
--- a/controller.py
+++ b/controller.py
@@ -439,7 +439,7 @@ class Controller(object):
         if self.auth_token:
             session.headers.update({'Authorization': 'Bearer ' + self.auth_token})
         verify = CA_CERT_PATH if self.ca_crt_exists else False
-        return session.get(path, verify=verify, stream=stream)
+        return session.get(path, verify=verify, stream=stream, timeout=(5, 10))
 
     def _is_leader(self):
         """
```
and it seemed to work around the issue (but it also generated spammy error logs due to the new timeout).

**Comment by rtheis** [comment] 2017-03-16 19:00
The PoC from @fasaxc worked great.  With the PoC, the test passed all 10 times that I ran it.  **Without** the PoC, the test usually fails more than 50% of the time.

**Comment by lxpollitt** [comment] 2017-03-16 21:09
When do you need an officially released fix for this?

**Comment by rtheis** [comment] 2017-03-16 21:29
We have a temporary workaround in place for this week.  It would be ideal for us to have an official fix released sometime next week.

**Comment by neiljerram** [comment] 2017-03-17 13:56
@rtheis In your reproduction steps you wrote

> 1. Stop k8s API and etcd
> [...]
> 3. Start k8s API and etcd

When etcd was restarted in (3), was it with the same data as it had in (1); or did you also blow away that data between (1) and (3) - or e.g. restart in some new environment with no existing data?

Just asking to make sure that we get our repro testing exactly right...

**Comment by rtheis** [comment] 2017-03-17 14:18
@neiljerram: The same data was used.

**Comment by neiljerram** [comment] 2017-03-17 22:12
So, from my testing, it appears that when the k8s API server is stopped, there is never any delay or unpredictability in the policy-controller's first detection of that, but there is a lot of variability in the timing out of policy-controller's subsequent attempts to reconnect.

I tried 10 iterations of:
- add a new namespace
- sleep 1
- kill API server
- wait 60 seconds
- restart API server
- observe policy-controller reconnection attempts.

In all 10 iterations, initial detection of the API server having gone away is within 0.5s, and corresponds to logs like

```
2017-03-17 14:12:12,504 7 ERROR Unhandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 307, in _manage_resource
  File "<string>", line 343, in _watch_resource
  File "site-packages/requests/models.py", line 702, in iter_lines
  File "site-packages/requests/models.py", line 663, in generate
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
2017-03-17 14:12:12,504 7 WARNING Re-starting watch on resource: Namespace
```

Then, in each iteration, the policy-controller tries to reconnect and, each time it fails, logs like this:
```
2017-03-17 14:14:20,696 7 ERROR Connection error querying: Namespace
Traceback (most recent call last):
  File "<string>", line 304, in _manage_resource
  File "<string>", line 390, in _sync_resources
  File "<string>", line 442, in _api_get
  File "site-packages/requests/sessions.py", line 480, in get
  File "site-packages/requests/sessions.py", line 468, in request
  File "site-packages/requests/sessions.py", line 576, in send
  File "site-packages/requests/adapters.py", line 437, in send
ConnectionError: HTTPSConnectionPool(host='172.17.0.3', port=6443): Max retries exceeded with url: /api/v1/namespaces (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9ee7cd9c50>: Failed to establish a new connection: [Errno 110] Operation timed out',))
```

In iteration 1, I see this connection error after 10s, then after 3s more, and then after every 2s more, until the API server is available again.

In iterations 2 through 7, I see that connection error only once after 64s.  (In other words, a single connection attempt that times out after 64s, instead of multiple connection attempts that time out more quickly.)

In iteration 8, I see a single connection attempt that times out after 127s.  (Although the API server was available again after about 60s.)

**Comment by neiljerram** [comment] 2017-03-17 22:20
There's also a difference in the `errno`s in the different connection timeouts:

- the 10s/3s/2s ones all have `[Errno 113] Host is unreachable`

- the 64s ones all have `[Errno 111] Connection refused`

- the 127s one has `[Errno 110] Operation timed out`.

**Comment by neiljerram** [comment] 2017-03-18 00:56
@rtheis I've posted what I think is the right fix for this (#77): it's exactly the same as Shaun's PoC that you've already tested, plus reducing the logging level for connection issues from exception to warning (because seeing the traceback every time isn't helpful).

Even though it should be the same as what you've already successfully tested, it would be a nice sanity check if you were able to test the proposed PR.

**Comment by rtheis** [comment] 2017-03-20 15:38
@neiljerram: The proposed PR was successful in my test.  It would be nice to eliminate the log spam when no changes occur in the cluster.

**Closed** 2017-03-20 16:42 UTC
Labels: priority/P1

**Comment by neiljerram** [comment] 2017-03-20 17:05
@rtheis With the PR as just merged, there shouldn't be any remaining (inappropriate) log spam.  Are you still seeing some?

**Comment by rtheis** [comment] 2017-03-20 20:13
@neiljerram: Here's the log spam that I'm seeing every 10 seconds with a master build.  The k8s API and etcd are available:

```
2017-03-20 20:06:36,768 5 WARNING Connection error: Namespace ...HTTPSConnectionPool(host='10.10.10.1', port=443): Read timed out.
2017-03-20 20:06:36,769 5 WARNING Re-starting watch on resource: Namespace
2017-03-20 20:06:36,769 5 WARNING Connection error: NetworkPolicy ...HTTPSConnectionPool(host='10.10.10.1', port=443): Read timed out.
2017-03-20 20:06:36,770 5 WARNING Re-starting watch on resource: NetworkPolicy
2017-03-20 20:06:36,889 5 WARNING Connection error: Pod ...HTTPSConnectionPool(host='10.10.10.1', port=443): Read timed out.
2017-03-20 20:06:36,889 5 WARNING Re-starting watch on resource: Pod
2017-03-20 20:06:37,771 5 INFO Syncing 'NetworkPolicy' objects
2017-03-20 20:06:37,773 5 INFO Syncing 'Namespace' objects
...
2017-03-20 20:06:37,817 5 INFO Done getting NetworkPolicy(s) - new resourceVersion: 17657
2017-03-20 20:06:37,817 5 INFO Done getting Namespace(s) - new resourceVersion: 17657
2017-03-20 20:06:37,819 5 INFO Starting watch on: https://10.10.10.1:443/api/v1/watch/namespaces
...
2017-03-20 20:06:37,821 5 INFO Starting watch on: https://10.10.10.1:443/apis/extensions/v1beta1/watch/networkpolicies
...
2017-03-20 20:06:37,849 5 INFO Emptied the event queue
2017-03-20 20:06:37,891 5 INFO Syncing 'Pod' objects
...
2017-03-20 20:06:37,922 5 INFO Done getting Pod(s) - new resourceVersion: 17657
2017-03-20 20:06:37,922 5 INFO Starting watch on: https://10.10.10.1:443/api/v1/watch/pods
...
2017-03-20 20:06:37,933 5 INFO Emptied the event queue
```

**Comment by neiljerram** [comment] 2017-03-21 15:27
@rtheis I've posted a further PR at #80 that I think addresses the excessive resyncs and logging that you were seeing during normal operation following #77.

I need to get internal review for that here, and would also appreciate your thoughts and test results, if you are able to give this a run.

**Comment by rtheis** [comment] 2017-03-21 16:56
@neiljerram: This does help with excessive resyncs and logging.  So that part seems good to me.  However, do we now have a timing window such that events during the normal timeout are lost?  Also, I'm wondering if the timeout should be increased?

**Comment by caseydavenport** [comment] 2017-03-21 17:01
@rtheis it shouldn't open any windows, since the controller will re-start the watch from the previous resource version, picking up where the previous watch left off.  If the resource version gets out of date, we'll receive a different error which kicks off a resync so we'll be up to date again.

**Comment by neiljerram** [comment] 2017-03-21 17:02
Thanks @rtheis.  No, I don't believe there is any window; the mechanism that avoids that is that the resource version: each time we issue a new read request, we ask for any updates since the last version that we knew about.

**Comment by rtheis** [comment] 2017-03-21 17:09
Thank you guys.  It sounds like we are good to go now.  I'll run a final test.

**Comment by neiljerram** [comment] 2017-03-21 17:16
:crossed_fingers:

**Comment by rtheis** [comment] 2017-03-21 17:22
@neiljerram: My test failed.  I see the following exception being repeated in the logs:

```
Traceback (most recent call last):
  File "<string>", line 311, in _manage_resource
  File "<string>", line 424, in _sync_resources
  File "site-packages/requests/models.py", line 808, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by neiljerram** [comment] 2017-03-21 17:27
I saw that when my test was accidentally blowing away the etcd store each time that it restarted the API server.  Then when I fixed that (to allow the etcd data to persist), that problem disappeared.  Is there any chance that that's happening in your test too?

**Comment by neiljerram** [comment] 2017-03-21 17:28
(Of course that may be another scenario that we want to fix - but perhaps a different one from what we've been focussing on for this issue.)

**Comment by rtheis** [comment] 2017-03-21 17:40
I didn't delete the etcd store.  I've been toggling between v0.5.2 and the master version and only have a problem with the master.

**Comment by rtheis** [comment] 2017-03-21 17:50
I'm going to rebuild and try again.

**Comment by rtheis** [comment] 2017-03-21 19:46
@neiljerram: My test environment was corrupted.  After a rebuild, your fix is working well.  My tests were successful.  Thank you.

**Comment by neiljerram** [comment] 2017-03-21 21:00
@rtheis That's good news - many thanks for digging into that further.

**Comment by caseydavenport** [comment] 2017-03-21 23:34
I've release v0.5.4 that includes @neiljerram's PRs.

Thanks a lot for the help, @rtheis!

**Comment by rtheis** [comment] 2017-03-22 10:56
Thank you.

**Comment by vinayakshnd** [comment] 2017-06-06 09:58
Hi @neiljerram ,

I am using v0.6.0 of kube-policy-controller. I am still getting the error that you faced during testing
`Traceback (most recent call last):
  File "<string>", line 324, in _manage_resource
  File "<string>", line 441, in _sync_resources
  File "site-packages/requests/models.py", line 866, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

You mentioned about the fix by allowing the etcd data to persist. Could you please explain a bit more about the fix. If I am not wrong etcd persist data on filesystem by-default.I am still new to etcd.

Thanks in advance.
